### PR TITLE
G castle level

### PR DESCRIPTION
**Pull request by BeneAlgirdas**

### CODE REVIEW

**Comment by MellowJay** [comment]
[[GRAPHICS] Castle Zone](https://trello.com/c/T7D1Id0n/83-graphics-castle-zone)

**Comment by MellowJay** [comment]
[[FEATURE] Castle Terrain Hitboxes](https://trello.com/c/0im1Ats9/77-feature-castle-terrain-hitboxes)

**Comment by MellowJay** [comment]
[[GRAPHICS] Player Character Size In Castle](https://trello.com/c/RRSsfyVB/127-graphics-player-character-size-in-castle)

**Review by MellowJay — CHANGES_REQUESTED** [review]
Ok, we have a new level. Cool 😎
I changed the player's order so that the player would be rendered last.
@PandaPandaa will add the moving camera to the castle scene.
The only things that should be changed:
- All of the candles should be flickering.
- I think the pit in the image below doesn't look good rotated in a top down perspective.
image

**Comment by PandaPandaa** [comment]
I added camera to follow player and camera boundaries.

**Comment by PandaPandaa** [comment]
[[GRAPHICS] Moving Camera In Castle](https://trello.com/c/Hr5J5Svk/126-graphics-moving-camera-in-castle)

**Review by MellowJay — COMMENTED** [review]
I tested the transition and it works. The altar lights up and then the player gets teleported to the castle.
Very nice 👍

**Comment by MellowJay** [comment]
[[FEATURES] Warp To Castle Zone](https://trello.com/c/DsagKmnT/128-features-warp-to-castle-zone)

**Pull request merged**
