### PR TITLE
Player Death

### PR DESCRIPTION
**Pull request by T-aut**
Added player death animation + UI menu + scene restart.

How to test:
start game in PlayerDeathPoC and while in play mode - set the players current health to 0.

### CODE REVIEW

**Comment by T-aut** [comment]
[[FEATURE] Player Death And Respawn To Scene Starting Point](https://trello.com/c/C1wJ06UF/118-feature-player-death-and-respawn-to-scene-starting-point)

**Comment by T-aut** [comment]
[[GRAPHICS] Player Death Animation](https://trello.com/c/qKCRDcWb/119-graphics-player-death-animation)

**Comment by MellowJay** [comment]
Dying works and looks cool. 😎👍

**Comment by T-aut** [comment]
@MellowJay could you maybe check whether all your functionality works well from your previous PR? Had to fix quite a few conflicts 😄 

Also, it seems that the fireball does not interact with the wolf enemy NPC
image

**Review by MellowJay — APPROVED** [review]
I fixed the fireball not colliding with the wolf. I think I pushed that error to dev on Thursday.
I checked and everything from my Fire Sword PR works. 👍

**Pull request merged**
