### PR TITLE
Added dash functionality and deadly stab combo.

### PR DESCRIPTION
**Pull request by MellowJay**
- Added "Dash" input for dashing. It is set to spacebar.
- Dashing costs a certain amount of stamina and moves the player in the appropriate direction.
- You can't dash through walls or other obstacles.
- There is a cooldown for dashing after every dash to prevent dash abuse.
- The distance, dash stamina cost and cooldown can all be configured. 
- There is also a timeframe after every dash for a deadly stab combo. This can also be configured.
- After dashing the player must have enough stamina for a normal attack and attack at the right time to perform the deadly stab combo.
- The deadly stab combo deals five times more damage than a normal attack.
- The deadly stab combo's attack animation is a bit slower than a normal attack's.

### CODE REVIEW

**Comment by MellowJay** [comment]
[[FEATURE] Roll/Dash](https://trello.com/c/5kFv5Ybi/61-feature-roll-dash)

**Comment by MellowJay** [comment]
[[FEATURE] Player Deadly Stab (Dagger + Roll/Dash) Combo](https://trello.com/c/36XcUO6n/120-feature-player-deadly-stab-dagger-roll-dash-combo)

**Comment by MellowJay** [comment]
The dash is implemented in the DashPoC scene. I will move it to the ForestZone scene before merging.

**Review by T-aut — APPROVED** [review]
Looked at .cs files, looked ok 🦓

**Pull request merged**
