### PR TITLE
Game intro

### PR DESCRIPTION
**Pull request by T-aut**
Added an intro scene with a timeline according to the script in our design document. Also createda scene loader with crossfade prefab which can now be used to load scenes seamlessly.

### CODE REVIEW

**Comment by T-aut** [comment]
[[FEATURE] Game Intro With Backstory](https://trello.com/c/GfuvqvrQ/59-feature-game-intro-with-backstory)

**Comment by T-aut** [comment]
[[TEXT] Game Intro Backstory](https://trello.com/c/l73Gy1zv/58-text-game-intro-backstory)

**Comment by T-aut** [comment]
God i hated working with the timeline 🆘

**Review by MellowJay — APPROVED** [review]
The intro is AMAZING! 🤩 Feels like we have a real game! 👍
I suggest you merge now.

**Pull request merged**
